project_id = "kfvmkdxnevfognngesrf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[edge_runtime]
enabled = true
port = 54324

[functions.audit-logger]
verify_jwt = true

[functions.rate-limiter]
verify_jwt = true

[functions.generate-receipt-url]
verify_jwt = true