// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/*
 * SECURITY NOTE: Public Supabase Configuration
 * 
 * The SUPABASE_PUBLISHABLE_KEY (also called anon key) is safe to expose in frontend code.
 * 
 * Why this is secure:
 * 1. The anon key is designed to be public and has very limited permissions
 * 2. All security is enforced by Row Level Security (RLS) policies in the database
 * 3. Users can only access data that RLS policies explicitly allow
 * 4. The key becomes "authenticated" when a user logs in, but still respects RLS
 * 5. Even if someone copies this key, they cannot access other users' data
 * 
 * What this key CANNOT do:
 * - Access other users' data (prevented by RLS)
 * - Perform admin operations (requires service role key)
 * - Bypass authentication requirements
 * - Read/write data without proper RLS policies
 * 
 * The actual security boundary is in the database via RLS policies, not the API key.
 */

// const SUPABASE_URL = "https://kfvmkdxnevfognngesrf.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmdm1rZHhuZXZmb2dubmdlc3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODE1MjgsImV4cCI6MjA2NjU1NzUyOH0.QI8dpfoXaRPg5VE70rBdScEyhRI1mh56ElcUeuj6FvY";

const SUPABASE_URL = "https://wllrommtrmlwlciaenzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbHJvbW10cm1sd2xjaWFlbnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjI1NzEsImV4cCI6MjA3MTg5ODU3MX0.NchuCHDm6qa5urmqgtQDhVhxM2pK656lATOI4vasnMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);