name: SQL Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Supabase CLI
        run: npm i -g supabase
      
      - name: Start local Supabase
        run: supabase start
      
      - name: Apply migrations
        run: supabase db reset --no-backup
      
      - name: Run pgTAP tests
        run: psql "postgres://postgres:postgres@localhost:54322/postgres" -f supabase/tests/rls.sql